// <auto-generated />
namespace BeerAppreciation.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class BeverageStyleTypeRefactor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BeverageStyleTypeRefactor));
        
        string IMigrationMetadata.Id
        {
            get { return "201411070336529_BeverageStyle-Type-Refactor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
