//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerAppreciation.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeerAppreciation.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Beer Appreciation Data Population Script
        ///-- Matt Granger 06/2014
        ///
        ///SET IDENTITY_INSERT [dbo].[Manufacturers] ON 
        ///
        ///INSERT [dbo].[Manufacturers] ([Id], [Name], [Description], [Country]) VALUES (1, N&apos;Yeastie Boys&apos;, NULL, N&apos;New Zealand&apos;)
        ///INSERT [dbo].[Manufacturers] ([Id], [Name], [Description], [Country]) VALUES (2, N&apos;Iron Bark Brewery&apos;, NULL, N&apos;Australia&apos;)
        ///INSERT [dbo].[Manufacturers] ([Id], [Name], [Description], [Country]) VALUES (3, N&apos;La Trappe&apos;, NULL, N&apos;Normandy&apos;)
        ///INSERT [dbo].[Manufacturers] ([ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataPopulationScript {
            get {
                return ResourceManager.GetString("DataPopulationScript", resourceCulture);
            }
        }
    }
}
